---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote-container
        image: kodekloud/examplevotingapp_vote:before
        imagePullPolicy: IfNotPresent
---
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: vote

spec:
  type: NodePort
  selector:
   app : vote
  ports:
  - port: 5000
    targetPort: 80
    nodePort: 31000
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-container
        image: redis:alpine
        volumeMounts:
        - name: redis-data
          mountPath: /data

      volumes:
      - name: redis-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vote

spec:
  selector:
   app : redis
  ports:
  - port: 6379
    targetPort: 6379
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-container
        image: kodekloud/examplevotingapp_worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-container
        image: postgres:9.4
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data

      volumes:
      - name: db-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote

spec:
  selector:
   app : db
  ports:
  - port: 5432
    targetPort: 5432
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result-container
        image: kodekloud/examplevotingapp_result:before
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: vote

spec:
  type: NodePort
  selector:
   app : result
  ports:
  - port: 5001
    targetPort: 80
    nodePort: 31001
    name: http
