---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      airflow: scheduler
  template:
    metadata:
      labels:
        airflow: scheduler
    spec:
      containers:
      - name: airflow-sch-container
        image: mlworks.azurecr.io/k8s-airflow-mlw:05
        imagePullPolicy: Always
        args: ["scheduler"]
        volumeMounts:
        - name: azure-dag
          mountPath: /root/airflow/dags
#        - name: susmita-airflow-configmap
#          mountPath: /root/airflow/airflow.cfg
      imagePullSecrets:
      - name : airflow-test
      volumes:
      - name: azure-dag
        persistentVolumeClaim:
          claimName: dag-fileshare-pvc
#      - name: susmita-airflow-configmap
#        configMap:
#          name: susmita-airflow-configmap