---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dag-fileshare-pv
  labels:
    usage: dag-fileshare-pv
spec:
  storageClassName: azurefile-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  azureFile:
    secretName: azure-file-secret
    shareName: airflowdag
    readOnly: false

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dag-fileshare-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: dag-fileshare-pv
